// server.js
// WebSocket game server for the friends-blackjack app.
// Rooms are held in memory only — fine for a casual session, wiped on server restart.
//
// Player identity is a persistent token generated by the client (stored in
// localStorage), NOT socket.id — see socketToken map below for why.
//
// HAND MODEL: each non-banker player's hand(s) live at room.hands[token] as
// an ARRAY of hand objects: [{ cards, bet, standing, doubled, fromSplit }].
// Normally length 1. Splitting a pair makes it length 2, each with its own
// bet and its own hit/stand/bust state, played in order. The banker never
// splits, so room.hands.banker stays a plain array of cards (not wrapped).
//
// Simplifications kept deliberately basic for v1:
//  - No re-splitting a hand that's already been split once.
//  - Split aces get dealt like any other split hand (one card, can still hit) —
//    real casinos often restrict split aces to exactly one extra card. Worth
//    tightening later if it matters to the group.
//  - A 21 on a split hand is a normal win (1:1), never a 3:2 "blackjack" —
//    that bonus is reserved for a natural on the original two-card deal,
//    same as standard casino rules.

const express = require("express");
const http = require("http");
const { Server } = require("socket.io");
const { createDeck, shuffle, deal, scoreHand, isBlackjack, isBust, cardBaseValue } = require("./deck");

const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: "*" } });

app.use(express.static("public"));
app.get("/health", (req, res) => res.json({ ok: true, rooms: Object.keys(rooms).length }));

const MIN_BET = 1;
const MAX_BET = 5;

const rooms = {};                 // { [code]: room }
const socketToken = new Map();    // socket.id -> token, rebuilt on every connect/reconnect

function makeRoomCode() {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let code;
  do {
    code = Array.from({ length: 5 }, () => chars[Math.floor(Math.random() * chars.length)]).join("");
  } while (rooms[code]);
  return code;
}

function newRoom(code, creatorToken, creatorName, roundsPerBanker) {
  return {
    code,
    roundsPerBanker,
    roundCount: 0,
    turnOrder: [creatorToken],
    bankerIndex: 0,
    players: {
      [creatorToken]: { id: creatorToken, name: creatorName, balance: 0 },
    },
    deck: [],
    bets: {},              // { token: amount } — the original per-round bet, set during betting phase
    hands: {},             // { token: [handObj, ...], banker: [...cards] }
    activeHandIndex: {},   // { token: 0 | 1 } — which of a player's hands they're currently acting on
    currentTurn: null,
    phase: "betting",      // betting | dealing | player_turns | banker_turn | payout
  };
}

function getBankerToken(room) {
  return room.turnOrder[room.bankerIndex];
}

function nonBankerTokens(room) {
  const bankerToken = getBankerToken(room);
  return room.turnOrder.filter((t) => t !== bankerToken);
}

function broadcastState(room) {
  io.to(room.code).emit("room_state", room);
}

function ensureShoe(room, cardsNeeded) {
  if (room.deck.length < cardsNeeded) {
    room.deck = shuffle(createDeck());
  }
}

function allHandsStanding(room, token) {
  return room.hands[token].every((h) => h.standing);
}

function firstUnresolvedHandIndex(room, token) {
  const idx = room.hands[token].findIndex((h) => !h.standing);
  return idx === -1 ? 0 : idx;
}

function currentHand(room, token) {
  return room.hands[token][room.activeHandIndex[token]];
}

function startDealing(room) {
  room.phase = "dealing";
  room.hands = { banker: [] };
  room.activeHandIndex = {};

  const players = nonBankerTokens(room);
  ensureShoe(room, (players.length + 1) * 2);

  for (const t of players) {
    room.hands[t] = [{ cards: [], bet: room.bets[t], standing: false, doubled: false, fromSplit: false }];
    room.activeHandIndex[t] = 0;
  }

  for (let round = 0; round < 2; round++) {
    for (const t of players) {
      room.hands[t][0].cards.push(...deal(room.deck, 1));
    }
    room.hands.banker.push(...deal(room.deck, 1));
  }

  const bankerBJ = isBlackjack(room.hands.banker);

  for (const t of players) {
    if (isBlackjack(room.hands[t][0].cards)) room.hands[t][0].standing = true;
  }

  if (bankerBJ) {
    // Skip straight to payout — no point playing out hands vs a banker natural.
    for (const t of players) room.hands[t].forEach((h) => (h.standing = true));
    resolvePayout(room);
    return;
  }

  room.phase = "player_turns";
  const firstToAct = players.find((t) => !allHandsStanding(room, t));
  room.currentTurn = firstToAct || null;
  if (!room.currentTurn) {
    runBankerTurn(room);
  } else {
    room.activeHandIndex[room.currentTurn] = firstUnresolvedHandIndex(room, room.currentTurn);
  }
}

// Called after a hand finishes (bust, stand, or double auto-stand). Moves to
// the player's other split hand if there is one and it's unresolved,
// otherwise moves to the next player, otherwise runs the banker's turn.
function advanceAfterHandDone(room) {
  const token = room.currentTurn;
  const hands = room.hands[token];
  const otherIdx = hands.length === 2 ? 1 - room.activeHandIndex[token] : -1;

  if (otherIdx !== -1 && !hands[otherIdx].standing) {
    room.activeHandIndex[token] = otherIdx;
    return;
  }

  const players = nonBankerTokens(room);
  const idx = players.indexOf(token);
  const next = players.slice(idx + 1).find((t) => !allHandsStanding(room, t));
  if (next) {
    room.currentTurn = next;
    room.activeHandIndex[next] = firstUnresolvedHandIndex(room, next);
  } else {
    room.currentTurn = null;
    runBankerTurn(room);
  }
}

function runBankerTurn(room) {
  room.phase = "banker_turn";
  while (scoreHand(room.hands.banker).total < 17) {
    room.hands.banker.push(...deal(room.deck, 1));
  }
  resolvePayout(room);
}

function resolvePayout(room) {
  const bankerToken = getBankerToken(room);
  const bankerHand = room.hands.banker;
  const bankerBJ = isBlackjack(bankerHand);
  const bankerBust = isBust(bankerHand);
  const bankerScore = scoreHand(bankerHand).total;

  const results = {};

  for (const t of nonBankerTokens(room)) {
    let totalDelta = 0;

    for (const hand of room.hands[t]) {
      const bet = hand.bet || 0;
      const isNaturalBJ = !hand.fromSplit && isBlackjack(hand.cards);
      const playerBust = isBust(hand.cards);
      let delta = 0;

      if (isNaturalBJ && bankerBJ) delta = 0;
      else if (isNaturalBJ && !bankerBJ) delta = bet * 1.5;
      else if (bankerBJ && !isNaturalBJ) delta = -bet;
      else if (playerBust) delta = -bet;
      else if (bankerBust) delta = bet;
      else {
        const playerScore = scoreHand(hand.cards).total;
        if (playerScore > bankerScore) delta = bet;
        else if (playerScore < bankerScore) delta = -bet;
        else delta = 0;
      }
      totalDelta += delta;
    }

    room.players[t].balance += totalDelta;
    room.players[bankerToken].balance -= totalDelta;
    results[t] = totalDelta;
  }

  room.roundCount += 1;
  if (room.roundCount % room.roundsPerBanker === 0) {
    room.bankerIndex = (room.bankerIndex + 1) % room.turnOrder.length;
  }

  room.lastResults = results;
  room.bets = {};
  room.currentTurn = null;
  room.activeHandIndex = {};
  room.phase = "betting";
}

function requireToken(socket) {
  return socketToken.get(socket.id);
}

// Shared guard for hit/stand/double/split — all four require it to be this
// player's active turn on an unresolved hand.
function guardActingPlayer(room, token) {
  if (!room || !token) return "Not connected to that room — try reloading";
  if (room.phase !== "player_turns" || room.currentTurn !== token) return "Not your turn";
  const hand = currentHand(room, token);
  if (!hand || hand.standing) return "That hand is already done";
  return null;
}

io.on("connection", (socket) => {
  console.log(`[connect] ${socket.id}`);

  socket.on("create_room", ({ name, roundsPerBanker, token }, cb) => {
    if (!token) return cb({ ok: false, error: "Missing player token" });
    const code = makeRoomCode();
    const room = newRoom(code, token, name, roundsPerBanker || 10);
    rooms[code] = room;
    socket.join(code);
    socketToken.set(socket.id, token);
    console.log(`[create_room] code=${code} by=${name} token=${token}`);
    cb({ ok: true, code });
    broadcastState(room);
  });

  socket.on("join_room", ({ code, name, token }, cb) => {
    if (!token) return cb({ ok: false, error: "Missing player token" });
    console.log(`[join_room] attempt code=${code} by=${name} token=${token}, known rooms=${Object.keys(rooms).join(",")}`);
    const room = rooms[code];
    if (!room) {
      console.log(`[join_room] FAILED — room ${code} not found`);
      return cb({ ok: false, error: "Room not found" });
    }

    socket.join(code);
    socketToken.set(socket.id, token);

    if (room.players[token]) {
      console.log(`[join_room] REJOIN — ${name} (${token}) back in ${code}`);
      cb({ ok: true, code });
      broadcastState(room);
      return;
    }

    room.players[token] = { id: token, name, balance: 0 };
    room.turnOrder.push(token);
    console.log(`[join_room] OK — ${name} joined ${code}, players now: ${room.turnOrder.length}`);
    cb({ ok: true, code });
    broadcastState(room);
  });

  socket.on("place_bet", ({ code, amount }, cb) => {
    const token = requireToken(socket);
    const room = rooms[code];
    if (!room || !token) return cb({ ok: false, error: "Not connected to that room — try reloading" });
    if (room.phase !== "betting") return cb({ ok: false, error: "Not accepting bets right now" });
    if (token === getBankerToken(room)) return cb({ ok: false, error: "Banker doesn't bet" });
    if (amount < MIN_BET || amount > MAX_BET) {
      return cb({ ok: false, error: `Bet must be between $${MIN_BET} and $${MAX_BET}` });
    }

    room.bets[token] = amount;
    cb({ ok: true });

    const players = nonBankerTokens(room);
    const allBetsIn = players.every((t) => room.bets[t] !== undefined);
    if (allBetsIn) startDealing(room);
    broadcastState(room);
  });

  socket.on("hit", ({ code }, cb) => {
    const token = requireToken(socket);
    const room = rooms[code];
    const err = guardActingPlayer(room, token);
    if (err) return cb({ ok: false, error: err });

    const hand = currentHand(room, token);
    hand.cards.push(...deal(room.deck, 1));
    if (isBust(hand.cards)) {
      hand.standing = true;
      advanceAfterHandDone(room);
    }
    cb({ ok: true });
    broadcastState(room);
  });

  socket.on("stand", ({ code }, cb) => {
    const token = requireToken(socket);
    const room = rooms[code];
    const err = guardActingPlayer(room, token);
    if (err) return cb({ ok: false, error: err });

    currentHand(room, token).standing = true;
    advanceAfterHandDone(room);
    cb({ ok: true });
    broadcastState(room);
  });

  socket.on("double", ({ code }, cb) => {
    const token = requireToken(socket);
    const room = rooms[code];
    const err = guardActingPlayer(room, token);
    if (err) return cb({ ok: false, error: err });

    const hand = currentHand(room, token);
    if (hand.cards.length !== 2 || hand.doubled) {
      return cb({ ok: false, error: "Can only double down on your first two cards" });
    }

    hand.bet *= 2;
    hand.doubled = true;
    hand.cards.push(...deal(room.deck, 1));
    hand.standing = true; // double down = exactly one more card, then forced stand
    advanceAfterHandDone(room);
    cb({ ok: true });
    broadcastState(room);
  });

  socket.on("split", ({ code }, cb) => {
    const token = requireToken(socket);
    const room = rooms[code];
    const err = guardActingPlayer(room, token);
    if (err) return cb({ ok: false, error: err });

    const hands = room.hands[token];
    if (hands.length !== 1) return cb({ ok: false, error: "You can only split once per round" });

    const hand = hands[0];
    if (hand.cards.length !== 2) return cb({ ok: false, error: "Can only split your first two cards" });
    if (cardBaseValue(hand.cards[0]) !== cardBaseValue(hand.cards[1])) {
      return cb({ ok: false, error: "Cards must match in value to split" });
    }

    const [cardA, cardB] = hand.cards;
    const bet = hand.bet;
    room.hands[token] = [
      { cards: [cardA, ...deal(room.deck, 1)], bet, standing: false, doubled: false, fromSplit: true },
      { cards: [cardB, ...deal(room.deck, 1)], bet, standing: false, doubled: false, fromSplit: true },
    ];
    room.activeHandIndex[token] = 0;
    cb({ ok: true });
    broadcastState(room);
  });

  socket.on("disconnect", () => {
    console.log(`[disconnect] ${socket.id}`);
    socketToken.delete(socket.id);
  });
});

const PORT = process.env.PORT || 3000;
server.listen(PORT, () => console.log(`Blackjack server listening on :${PORT}`));
