// server.js
// WebSocket game server for the friends-blackjack app.
// Rooms are held in memory only — fine for a casual session, wiped on server restart.
//
// Player identity is a persistent token generated by the client (stored in
// localStorage), NOT socket.id. socket.id changes every time a phone's
// connection drops and reconnects (switching wifi/cellular, backgrounding the
// app, etc.) — keying game state off it made every reconnect create a ghost
// player. The token survives reconnects and page reloads.

const express = require("express");
const http = require("http");
const { Server } = require("socket.io");
const { createDeck, shuffle, deal, scoreHand, isBlackjack, isBust } = require("./deck");

const app = express();
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: "*" } });

app.use(express.static("public"));
app.get("/health", (req, res) => res.json({ ok: true, rooms: Object.keys(rooms).length }));

const MIN_BET = 1;
const MAX_BET = 5;

// In-memory room store: { [code]: room }
const rooms = {};

// Which socket is currently "live" for a given player token, so we know where
// to send targeted messages and who's allowed to act. Rebuilt on every
// connect/reconnect/rejoin.
const socketToken = new Map(); // socket.id -> token

function makeRoomCode() {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no ambiguous chars
  let code;
  do {
    code = Array.from({ length: 5 }, () => chars[Math.floor(Math.random() * chars.length)]).join("");
  } while (rooms[code]);
  return code;
}

function newRoom(code, creatorToken, creatorName, roundsPerBanker) {
  return {
    code,
    roundsPerBanker,
    roundCount: 0,
    turnOrder: [creatorToken],     // join order, creator first — tokens, not socket ids
    bankerIndex: 0,                // index into turnOrder
    players: {
      [creatorToken]: { id: creatorToken, name: creatorName, balance: 0 },
    },
    deck: [],
    bets: {},                      // { token: amount }, excludes current banker
    hands: {},                     // { token: [...cards] }, includes "banker" key
    standing: {},                  // { token: true } once stood/busted/blackjack
    currentTurn: null,
    phase: "betting",              // betting | dealing | player_turns | banker_turn | payout
  };
}

function getBankerToken(room) {
  return room.turnOrder[room.bankerIndex];
}

function nonBankerTokens(room) {
  const bankerToken = getBankerToken(room);
  return room.turnOrder.filter((t) => t !== bankerToken);
}

function broadcastState(room) {
  io.to(room.code).emit("room_state", room);
}

function ensureShoe(room, cardsNeeded) {
  if (room.deck.length < cardsNeeded) {
    room.deck = shuffle(createDeck());
  }
}

function startDealing(room) {
  room.phase = "dealing";
  room.hands = { banker: [] };
  room.standing = {};

  const players = nonBankerTokens(room);
  ensureShoe(room, (players.length + 1) * 2);

  for (const t of players) room.hands[t] = [];

  for (let round = 0; round < 2; round++) {
    for (const t of players) {
      room.hands[t].push(...deal(room.deck, 1));
    }
    room.hands.banker.push(...deal(room.deck, 1));
  }

  const bankerBJ = isBlackjack(room.hands.banker);

  for (const t of players) {
    if (isBlackjack(room.hands[t])) room.standing[t] = true;
  }

  if (bankerBJ) {
    for (const t of players) room.standing[t] = true;
    resolvePayout(room);
    return;
  }

  room.phase = "player_turns";
  const firstToAct = players.find((t) => !room.standing[t]);
  room.currentTurn = firstToAct || null;
  if (!room.currentTurn) {
    runBankerTurn(room);
  }
}

function advanceTurn(room) {
  const players = nonBankerTokens(room);
  const idx = players.indexOf(room.currentTurn);
  const next = players.slice(idx + 1).find((t) => !room.standing[t]);
  if (next) {
    room.currentTurn = next;
  } else {
    room.currentTurn = null;
    runBankerTurn(room);
  }
}

function runBankerTurn(room) {
  room.phase = "banker_turn";
  while (scoreHand(room.hands.banker).total < 17) {
    room.hands.banker.push(...deal(room.deck, 1));
  }
  resolvePayout(room);
}

function resolvePayout(room) {
  const bankerToken = getBankerToken(room);
  const bankerHand = room.hands.banker;
  const bankerBJ = isBlackjack(bankerHand);
  const bankerBust = isBust(bankerHand);
  const bankerScore = scoreHand(bankerHand).total;

  const results = {};

  for (const t of nonBankerTokens(room)) {
    const hand = room.hands[t];
    const bet = room.bets[t] || 0;
    const playerBJ = isBlackjack(hand);
    const playerBust = isBust(hand);
    let delta = 0;

    if (playerBJ && bankerBJ) delta = 0;
    else if (playerBJ && !bankerBJ) delta = bet * 1.5;
    else if (bankerBJ && !playerBJ) delta = -bet;
    else if (playerBust) delta = -bet;
    else if (bankerBust) delta = bet;
    else {
      const playerScore = scoreHand(hand).total;
      if (playerScore > bankerScore) delta = bet;
      else if (playerScore < bankerScore) delta = -bet;
      else delta = 0;
    }

    room.players[t].balance += delta;
    room.players[bankerToken].balance -= delta;
    results[t] = delta;
  }

  room.roundCount += 1;
  if (room.roundCount % room.roundsPerBanker === 0) {
    room.bankerIndex = (room.bankerIndex + 1) % room.turnOrder.length;
  }

  room.lastResults = results;
  room.bets = {};
  room.currentTurn = null;
  room.phase = "betting";
}

function requireToken(socket) {
  return socketToken.get(socket.id);
}

io.on("connection", (socket) => {
  console.log(`[connect] ${socket.id}`);

  socket.on("create_room", ({ name, roundsPerBanker, token }, cb) => {
    if (!token) return cb({ ok: false, error: "Missing player token" });
    const code = makeRoomCode();
    const room = newRoom(code, token, name, roundsPerBanker || 10);
    rooms[code] = room;
    socket.join(code);
    socketToken.set(socket.id, token);
    console.log(`[create_room] code=${code} by=${name} token=${token}`);
    cb({ ok: true, code });
    broadcastState(room);
  });

  socket.on("join_room", ({ code, name, token }, cb) => {
    if (!token) return cb({ ok: false, error: "Missing player token" });
    console.log(`[join_room] attempt code=${code} by=${name} token=${token}, known rooms=${Object.keys(rooms).join(",")}`);
    const room = rooms[code];
    if (!room) {
      console.log(`[join_room] FAILED — room ${code} not found`);
      return cb({ ok: false, error: "Room not found" });
    }

    socket.join(code);
    socketToken.set(socket.id, token);

    if (room.players[token]) {
      // Reconnect / rejoin — same player, just a fresh socket. Don't touch turnOrder or balance.
      console.log(`[join_room] REJOIN — ${name} (${token}) back in ${code}`);
      cb({ ok: true, code });
      broadcastState(room);
      return;
    }

    room.players[token] = { id: token, name, balance: 0 };
    room.turnOrder.push(token);
    console.log(`[join_room] OK — ${name} joined ${code}, players now: ${room.turnOrder.length}`);
    cb({ ok: true, code });
    broadcastState(room);
  });

  socket.on("place_bet", ({ code, amount }, cb) => {
    const token = requireToken(socket);
    const room = rooms[code];
    if (!room || !token) return cb({ ok: false, error: "Not connected to that room — try reloading" });
    if (room.phase !== "betting") return cb({ ok: false, error: "Not accepting bets right now" });
    if (token === getBankerToken(room)) return cb({ ok: false, error: "Banker doesn't bet" });
    if (amount < MIN_BET || amount > MAX_BET) {
      return cb({ ok: false, error: `Bet must be between $${MIN_BET} and $${MAX_BET}` });
    }

    room.bets[token] = amount;
    cb({ ok: true });

    const players = nonBankerTokens(room);
    const allBetsIn = players.every((t) => room.bets[t] !== undefined);
    if (allBetsIn) startDealing(room);
    broadcastState(room);
  });

  socket.on("hit", ({ code }, cb) => {
    const token = requireToken(socket);
    const room = rooms[code];
    if (!room || !token || room.phase !== "player_turns" || room.currentTurn !== token) {
      return cb({ ok: false, error: "Not your turn" });
    }
    room.hands[token].push(...deal(room.deck, 1));
    if (isBust(room.hands[token])) {
      room.standing[token] = true;
      advanceTurn(room);
    }
    cb({ ok: true });
    broadcastState(room);
  });

  socket.on("stand", ({ code }, cb) => {
    const token = requireToken(socket);
    const room = rooms[code];
    if (!room || !token || room.phase !== "player_turns" || room.currentTurn !== token) {
      return cb({ ok: false, error: "Not your turn" });
    }
    room.standing[token] = true;
    advanceTurn(room);
    cb({ ok: true });
    broadcastState(room);
  });

  socket.on("disconnect", () => {
    console.log(`[disconnect] ${socket.id}`);
    socketToken.delete(socket.id);
    // Player stays in room state (balance preserved) — they'll reattach on
    // reconnect since the client auto-rejoins using the same stored token.
  });
});

const PORT = process.env.PORT || 3000;
server.listen(PORT, () => console.log(`Blackjack server listening on :${PORT}`));
